# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\wwwww.000\PycharmProjects\pyqt5\new_jingmeijiemian\quicreator.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!
import sys
from PyQt5 import QtCore, QtGui, QtWidgets
'''这是改造版本  原来的是普通类传入窗体类，然后实例化（见备份），现在是直接继承选项卡类'''
class ouwai_table_tab_widget(QtWidgets.QTabWidget):  #创建类继承QTabWidget窗体
    def __init__(self):                              #初始化窗体
        super(ouwai_table_tab_widget,self).__init__()
        self.setupUi()
    def setupUi(self):
        '''9999999999创建选项卡tabwidget'''
        '''901创建选项卡tab1'''
        self.tab1 = QtWidgets.QWidget()#####################   创建选项卡tab1
        self.tab1.setObjectName("tab1")
        self.tab1.setObjectName("tab1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab1)#在选项卡1中创建——垂直布局00001
        self.verticalLayout.setObjectName("verticalLayout")
        '''#在tab1选项卡中创建GroupBox分组框'''
        self.groupBox = QtWidgets.QGroupBox(self.tab1)  #在tab1选项卡中创建GroupBox分组框
        self.groupBox.setStyleSheet("")
        self.groupBox.setCheckable(True)
        self.groupBox.setObjectName("groupBox")
        '''在分组框里面创建网格布局0002'''
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        '''创建标签'''
        self.lab = QtWidgets.QLabel(self.groupBox)
        self.lab.setAlignment(QtCore.Qt.AlignCenter)
        self.lab.setObjectName("lab")
        '''标签加入网格'''
        self.gridLayout_2.addWidget(self.lab, 0, 0, 1, 1)
        '''文本框加入网格'''
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_2.addWidget(self.lineEdit, 0, 1, 1, 6)

        self.rbtn1 = QtWidgets.QRadioButton(self.groupBox)
        self.rbtn1.setObjectName("rbtn1")
        self.gridLayout_2.addWidget(self.rbtn1, 1, 0, 1, 1)
        '''单选框加入网格'''
        self.rbtn2 = QtWidgets.QRadioButton(self.groupBox)
        self.rbtn2.setObjectName("rbtn2")
        self.gridLayout_2.addWidget(self.rbtn2, 1, 1, 1, 1)
        '''下面是3个复选框加入网格'''
        self.ck1 = QtWidgets.QCheckBox(self.groupBox)
        self.ck1.setObjectName("ck1")
        self.gridLayout_2.addWidget(self.ck1, 1, 2, 1, 1)
        self.ck2 = QtWidgets.QCheckBox(self.groupBox)
        self.ck2.setChecked(False)
        self.ck2.setObjectName("ck2")
        self.gridLayout_2.addWidget(self.ck2, 1, 3, 1, 1)
        self.ck3 = QtWidgets.QCheckBox(self.groupBox)
        self.ck3.setObjectName("ck3")
        self.gridLayout_2.addWidget(self.ck3, 1, 4, 1, 1)

        '''下拉框加入网格'''
        self.cbox1 = QtWidgets.QComboBox(self.groupBox)
        self.cbox1.setMaximumSize(QtCore.QSize(16777215, 28))
        self.cbox1.setObjectName("cbox1")
        self.gridLayout_2.addWidget(self.cbox1, 1, 5, 1, 1)
        self.cbox2 = QtWidgets.QComboBox(self.groupBox)
        self.cbox2.setMaximumSize(QtCore.QSize(16777215, 28))
        self.cbox2.setObjectName("cbox2")
        self.gridLayout_2.addWidget(self.cbox2, 1, 6, 1, 1)
        '''下面是俺就提示信息 '''
        self.btnInfo = QtWidgets.QPushButton(self.groupBox)
        self.btnInfo.setObjectName("btnInfo")
        self.gridLayout_2.addWidget(self.btnInfo, 2, 0, 1, 1)
        self.btnQuestion = QtWidgets.QPushButton(self.groupBox)
        self.btnQuestion.setObjectName("btnQuestion")
        self.gridLayout_2.addWidget(self.btnQuestion, 2, 1, 1, 1)
        self.btnError = QtWidgets.QPushButton(self.groupBox)
        self.btnError.setObjectName("btnError")
        self.gridLayout_2.addWidget(self.btnError, 2, 2, 1, 1)
        self.btnInput = QtWidgets.QPushButton(self.groupBox)
        self.btnInput.setObjectName("btnInput")
        self.gridLayout_2.addWidget(self.btnInput, 2, 3, 1, 1)
        self.btnInputPwd = QtWidgets.QPushButton(self.groupBox)
        self.btnInputPwd.setObjectName("btnInputPwd")
        self.gridLayout_2.addWidget(self.btnInputPwd, 2, 4, 1, 1)
        self.btnInputcbox = QtWidgets.QPushButton(self.groupBox)
        self.btnInputcbox.setObjectName("btnInputcbox")
        self.gridLayout_2.addWidget(self.btnInputcbox, 2, 5, 1, 1)
        self.btnWidget = QtWidgets.QPushButton(self.groupBox)
        self.btnWidget.setObjectName("btnWidget")
        self.gridLayout_2.addWidget(self.btnWidget, 2, 6, 1, 1)
        '''下面是spinbox，也在分组框里面'''
        self.spinBox = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout_2.addWidget(self.spinBox, 3, 0, 1, 1)

        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.gridLayout_2.addWidget(self.doubleSpinBox, 3, 1, 1, 1)

        self.timeEdit = QtWidgets.QTimeEdit(self.groupBox)
        self.timeEdit.setObjectName("timeEdit")
        self.gridLayout_2.addWidget(self.timeEdit, 3, 2, 1, 1)
        '''日期编辑框'''
        self.dateEdit = QtWidgets.QDateEdit(self.groupBox)
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName("dateEdit")
        self.gridLayout_2.addWidget(self.dateEdit, 3, 3, 1, 2)

        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.groupBox)
        self.dateTimeEdit.setCalendarPopup(True)
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.gridLayout_2.addWidget(self.dateTimeEdit, 3, 5, 1, 2)
        '''#水平拖动按钮'''
        self.horizontalSlider = QtWidgets.QSlider(self.groupBox)
        self.horizontalSlider.setMaximum(100)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.gridLayout_2.addWidget(self.horizontalSlider, 4, 0, 1, 3)
        '''水平京都条加入网格'''
        self.progressBar = QtWidgets.QProgressBar(self.groupBox)
        self.progressBar.setMaximumSize(QtCore.QSize(16777215, 18))
        self.progressBar.setObjectName("progressBar")
        self.gridLayout_2.addWidget(self.progressBar, 4, 3, 1, 4)
        '''多行文本框'''
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.groupBox)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.gridLayout_2.addWidget(self.plainTextEdit, 5, 0, 1, 7)
        '''垂直布局中加入分组框   分组框里面又网格布局'''
        self.verticalLayout.addWidget(self.groupBox)
        '''选项卡1加入选项卡中'''
        self.addTab(self.tab1, "")
        '''902创建选项卡2'''
        self.tab2 = QtWidgets.QWidget()
        self.tab2.setObjectName("tab2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.tab2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tableWidget = QtWidgets.QTableWidget(self.tab2)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.horizontalLayout.addWidget(self.tableWidget)
        '''加入选项卡2'''
        self.addTab(self.tab2, "")
        '''903创建选项卡3'''
        self.tab3 = QtWidgets.QWidget()
        self.tab3.setObjectName("tab3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.tab3)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.widgetLeft = QtWidgets.QWidget(self.tab3)
        self.widgetLeft.setMinimumSize(QtCore.QSize(80, 0))
        self.widgetLeft.setObjectName("widgetLeft")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widgetLeft)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btn1 = QtWidgets.QPushButton(self.widgetLeft)
        self.btn1.setChecked(False)
        self.btn1.setObjectName("btn1")
        self.verticalLayout_2.addWidget(self.btn1)
        self.btn2 = QtWidgets.QPushButton(self.widgetLeft)
        self.btn2.setObjectName("btn2")
        self.verticalLayout_2.addWidget(self.btn2)
        self.btn3 = QtWidgets.QPushButton(self.widgetLeft)
        self.btn3.setObjectName("btn3")
        self.verticalLayout_2.addWidget(self.btn3)
        spacerItem = QtWidgets.QSpacerItem(20, 222, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout_7.addWidget(self.widgetLeft)
        self.stackedWidget = QtWidgets.QStackedWidget(self.tab3)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page1 = QtWidgets.QWidget()
        self.page1.setObjectName("page1")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.page1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widgetTop = QtWidgets.QWidget(self.page1)
        self.widgetTop.setObjectName("widgetTop")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widgetTop)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tbtn1 = QtWidgets.QToolButton(self.widgetTop)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbtn1.sizePolicy().hasHeightForWidth())
        self.tbtn1.setSizePolicy(sizePolicy)
        self.tbtn1.setObjectName("tbtn1")
        self.horizontalLayout_2.addWidget(self.tbtn1)
        self.tbtn2 = QtWidgets.QToolButton(self.widgetTop)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbtn2.sizePolicy().hasHeightForWidth())
        self.tbtn2.setSizePolicy(sizePolicy)
        self.tbtn2.setObjectName("tbtn2")
        self.horizontalLayout_2.addWidget(self.tbtn2)
        self.tbtn3 = QtWidgets.QToolButton(self.widgetTop)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbtn3.sizePolicy().hasHeightForWidth())
        self.tbtn3.setSizePolicy(sizePolicy)
        self.tbtn3.setObjectName("tbtn3")
        self.horizontalLayout_2.addWidget(self.tbtn3)
        self.verticalLayout_4.addWidget(self.widgetTop)
        self.widget = QtWidgets.QWidget(self.page1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.verticalLayout_4.addWidget(self.widget)
        self.widgetBottom = QtWidgets.QWidget(self.page1)
        self.widgetBottom.setMaximumSize(QtCore.QSize(16777215, 30))
        self.widgetBottom.setObjectName("widgetBottom")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widgetBottom)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lab1 = QtWidgets.QLabel(self.widgetBottom)
        self.lab1.setObjectName("lab1")
        self.horizontalLayout_3.addWidget(self.lab1)
        self.line1 = QtWidgets.QFrame(self.widgetBottom)
        self.line1.setMaximumSize(QtCore.QSize(1, 16777215))
        self.line1.setFrameShape(QtWidgets.QFrame.VLine)
        self.line1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line1.setObjectName("line1")
        self.horizontalLayout_3.addWidget(self.line1)
        self.lab2 = QtWidgets.QLabel(self.widgetBottom)
        self.lab2.setObjectName("lab2")
        self.horizontalLayout_3.addWidget(self.lab2)
        self.line2 = QtWidgets.QFrame(self.widgetBottom)
        self.line2.setMaximumSize(QtCore.QSize(1, 16777215))
        self.line2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line2.setObjectName("line2")
        self.horizontalLayout_3.addWidget(self.line2)
        self.lab3 = QtWidgets.QLabel(self.widgetBottom)
        self.lab3.setObjectName("lab3")
        self.horizontalLayout_3.addWidget(self.lab3)
        self.line3 = QtWidgets.QFrame(self.widgetBottom)
        self.line3.setMaximumSize(QtCore.QSize(1, 16777215))
        self.line3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line3.setObjectName("line3")
        self.horizontalLayout_3.addWidget(self.line3)
        self.lab4 = QtWidgets.QLabel(self.widgetBottom)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lab4.sizePolicy().hasHeightForWidth())
        self.lab4.setSizePolicy(sizePolicy)
        self.lab4.setObjectName("lab4")
        self.horizontalLayout_3.addWidget(self.lab4)
        self.verticalLayout_4.addWidget(self.widgetBottom)
        self.stackedWidget.addWidget(self.page1)
        self.page2 = QtWidgets.QWidget()
        self.page2.setObjectName("page2")
        self.stackedWidget.addWidget(self.page2)
        self.page3 = QtWidgets.QWidget()
        self.page3.setObjectName("page3")
        self.stackedWidget.addWidget(self.page3)
        self.horizontalLayout_7.addWidget(self.stackedWidget)
        self.verticalSlider = QtWidgets.QSlider(self.tab3)
        self.verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider.setObjectName("verticalSlider")
        self.horizontalLayout_7.addWidget(self.verticalSlider)
        self.verticalScrollBar = QtWidgets.QScrollBar(self.tab3)
        self.verticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")
        self.horizontalLayout_7.addWidget(self.verticalScrollBar)
        '''加入选项卡3'''
        self.addTab(self.tab3, "")
        '''904创建选项卡4'''
        self.tab4 = QtWidgets.QWidget()
        self.tab4.setObjectName("tab4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.tab4)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.treeWidget = QtWidgets.QTreeWidget(self.tab4)
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setText(0, "1")
        self.horizontalLayout_4.addWidget(self.treeWidget)
        self.listWidget = QtWidgets.QListWidget(self.tab4)
        self.listWidget.setObjectName("listWidget")
        self.horizontalLayout_4.addWidget(self.listWidget)
        self.addTab(self.tab4, "")
        '''905创建选项卡5'''
        self.tab5 = QtWidgets.QWidget()
        self.tab5.setObjectName("tab5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.tab5)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.calendarWidget1 = QtWidgets.QCalendarWidget(self.tab5)
        self.calendarWidget1.setObjectName("calendarWidget1")
        self.horizontalLayout_5.addWidget(self.calendarWidget1)
        self.calendarWidget2 = QtWidgets.QCalendarWidget(self.tab5)
        self.calendarWidget2.setGridVisible(True)
        self.calendarWidget2.setObjectName("calendarWidget2")
        self.horizontalLayout_5.addWidget(self.calendarWidget2)
        self.addTab(self.tab5, "")
        '''906创建选项卡6'''
        self.tab6 = QtWidgets.QWidget()
        self.tab6.setObjectName("tab6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.tab6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab6)
        self.tabWidget_2.setTabPosition(QtWidgets.QTabWidget.West)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tabWidget_2.addTab(self.tab, "")
        ''' 907创建选项卡'''
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.tabWidget_2.addTab(self.tab_7, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget_2.addTab(self.tab_2, "")
        self.horizontalLayout_6.addWidget(self.tabWidget_2)
        self.tabWidget_3 = QtWidgets.QTabWidget(self.tab6)
        self.tabWidget_3.setTabPosition(QtWidgets.QTabWidget.South)
        self.tabWidget_3.setObjectName("tabWidget_3")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget_3.addTab(self.tab_3, "")
        ''' 908创建选项卡'''
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.tabWidget_3.addTab(self.tab_8, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabWidget_3.addTab(self.tab_4, "")
        self.horizontalLayout_6.addWidget(self.tabWidget_3)
        self.tabWidget_4 = QtWidgets.QTabWidget(self.tab6)
        self.tabWidget_4.setTabPosition(QtWidgets.QTabWidget.East)
        self.tabWidget_4.setObjectName("tabWidget_4")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.tabWidget_4.addTab(self.tab_5, "")
        ''' 908创建选项卡'''
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.tabWidget_4.addTab(self.tab_9, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.tabWidget_4.addTab(self.tab_6, "")
        self.horizontalLayout_6.addWidget(self.tabWidget_4)
        self.addTab(self.tab6, "")
        self.tab7 = QtWidgets.QWidget()
        self.tab7.setObjectName("tab7")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab7)
        self.verticalLayout_3.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widgetPanel = QtWidgets.QWidget(self.tab7)
        self.widgetPanel.setObjectName("widgetPanel")
        self.verticalLayout_3.addWidget(self.widgetPanel)
        self.addTab(self.tab7, "")
        self.tab8 = QtWidgets.QWidget()
        self.tab8.setObjectName("tab8")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab8)
        self.verticalLayout_5.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.widgetFontPanel = QtWidgets.QWidget(self.tab8)
        self.widgetFontPanel.setObjectName("widgetFontPanel")
        self.verticalLayout_5.addWidget(self.widgetFontPanel)
        self.addTab(self.tab8, "")
        ''' 909创建选项卡'''
        self.tab9 = QtWidgets.QWidget()
        self.tab9.setObjectName("tab9")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab9)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.btnUIDemo1 = QtWidgets.QPushButton(self.tab9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnUIDemo1.sizePolicy().hasHeightForWidth())
        self.btnUIDemo1.setSizePolicy(sizePolicy)
        self.btnUIDemo1.setObjectName("btnUIDemo1")
        self.gridLayout_4.addWidget(self.btnUIDemo1, 0, 0, 1, 1)
        self.btnUIDemo2 = QtWidgets.QPushButton(self.tab9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnUIDemo2.sizePolicy().hasHeightForWidth())
        self.btnUIDemo2.setSizePolicy(sizePolicy)
        self.btnUIDemo2.setObjectName("btnUIDemo2")
        self.gridLayout_4.addWidget(self.btnUIDemo2, 0, 1, 1, 1)
        self.btnUIDemo3 = QtWidgets.QPushButton(self.tab9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnUIDemo3.sizePolicy().hasHeightForWidth())
        self.btnUIDemo3.setSizePolicy(sizePolicy)
        self.btnUIDemo3.setObjectName("btnUIDemo3")
        self.gridLayout_4.addWidget(self.btnUIDemo3, 0, 2, 1, 1)
        self.btnUIDemo4 = QtWidgets.QPushButton(self.tab9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnUIDemo4.sizePolicy().hasHeightForWidth())
        self.btnUIDemo4.setSizePolicy(sizePolicy)
        self.btnUIDemo4.setObjectName("btnUIDemo4")
        self.gridLayout_4.addWidget(self.btnUIDemo4, 0, 3, 1, 1)
        self.btnUIDemo5 = QtWidgets.QPushButton(self.tab9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnUIDemo5.sizePolicy().hasHeightForWidth())
        self.btnUIDemo5.setSizePolicy(sizePolicy)
        self.btnUIDemo5.setObjectName("btnUIDemo5")
        self.gridLayout_4.addWidget(self.btnUIDemo5, 1, 0, 1, 1)
        self.btnUIDemo6 = QtWidgets.QPushButton(self.tab9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnUIDemo6.sizePolicy().hasHeightForWidth())
        self.btnUIDemo6.setSizePolicy(sizePolicy)
        self.btnUIDemo6.setObjectName("btnUIDemo6")
        self.gridLayout_4.addWidget(self.btnUIDemo6, 1, 1, 1, 1)
        self.btnUIDemo7 = QtWidgets.QPushButton(self.tab9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnUIDemo7.sizePolicy().hasHeightForWidth())
        self.btnUIDemo7.setSizePolicy(sizePolicy)
        self.btnUIDemo7.setObjectName("btnUIDemo7")
        self.gridLayout_4.addWidget(self.btnUIDemo7, 1, 2, 1, 1)
        self.btnUIDemo8 = QtWidgets.QPushButton(self.tab9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnUIDemo8.sizePolicy().hasHeightForWidth())
        self.btnUIDemo8.setSizePolicy(sizePolicy)
        self.btnUIDemo8.setObjectName("btnUIDemo8")
        self.gridLayout_4.addWidget(self.btnUIDemo8, 1, 3, 1, 1)
        self.addTab(self.tab9, "")
        ''' 910创建选项卡'''
        self.tab10 = QtWidgets.QWidget()
        self.tab10.setObjectName("tab10")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab10)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.widgetVideo = QtWidgets.QWidget(self.tab10)
        self.widgetVideo.setObjectName("widgetVideo")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.widgetVideo)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.labCh1 = QtWidgets.QLabel(self.widgetVideo)
        self.labCh1.setAlignment(QtCore.Qt.AlignCenter)
        self.labCh1.setObjectName("labCh1")
        self.gridLayout_5.addWidget(self.labCh1, 0, 0, 1, 1)
        self.labCh2 = QtWidgets.QLabel(self.widgetVideo)
        self.labCh2.setAlignment(QtCore.Qt.AlignCenter)
        self.labCh2.setObjectName("labCh2")
        self.gridLayout_5.addWidget(self.labCh2, 0, 1, 1, 1)
        self.labCh3 = QtWidgets.QLabel(self.widgetVideo)
        self.labCh3.setAlignment(QtCore.Qt.AlignCenter)
        self.labCh3.setObjectName("labCh3")
        self.gridLayout_5.addWidget(self.labCh3, 0, 2, 1, 1)
        self.labCh4 = QtWidgets.QLabel(self.widgetVideo)
        self.labCh4.setAlignment(QtCore.Qt.AlignCenter)
        self.labCh4.setObjectName("labCh4")
        self.gridLayout_5.addWidget(self.labCh4, 0, 3, 1, 1)
        self.labCh5 = QtWidgets.QLabel(self.widgetVideo)
        self.labCh5.setAlignment(QtCore.Qt.AlignCenter)
        self.labCh5.setObjectName("labCh5")
        self.gridLayout_5.addWidget(self.labCh5, 0, 4, 1, 1)
        self.labCh6 = QtWidgets.QLabel(self.widgetVideo)
        self.labCh6.setAlignment(QtCore.Qt.AlignCenter)
        self.labCh6.setObjectName("labCh6")
        self.gridLayout_5.addWidget(self.labCh6, 1, 0, 1, 1)
        self.labCh7 = QtWidgets.QLabel(self.widgetVideo)
        self.labCh7.setAlignment(QtCore.Qt.AlignCenter)
        self.labCh7.setObjectName("labCh7")
        self.gridLayout_5.addWidget(self.labCh7, 1, 1, 1, 1)
        self.labCh8 = QtWidgets.QLabel(self.widgetVideo)
        self.labCh8.setAlignment(QtCore.Qt.AlignCenter)
        self.labCh8.setObjectName("labCh8")
        self.gridLayout_5.addWidget(self.labCh8, 1, 2, 1, 1)
        self.labCh9 = QtWidgets.QLabel(self.widgetVideo)
        self.labCh9.setAlignment(QtCore.Qt.AlignCenter)
        self.labCh9.setObjectName("labCh9")
        self.gridLayout_5.addWidget(self.labCh9, 1, 3, 1, 1)
        self.labCh10 = QtWidgets.QLabel(self.widgetVideo)
        self.labCh10.setAlignment(QtCore.Qt.AlignCenter)
        self.labCh10.setObjectName("labCh10")
        self.gridLayout_5.addWidget(self.labCh10, 1, 4, 1, 1)
        self.verticalLayout_6.addWidget(self.widgetVideo)
        self.addTab(self.tab10, "")
        self.retranslateUi()
        self.setCurrentIndex(0)
        self.stackedWidget.setCurrentIndex(0)
        # self.tabWidget_2.setCurrentIndex(2)
        # self.tabWidget_3.setCurrentIndex(0)
        # self.tabWidget_4.setCurrentIndex(2)
        self.horizontalSlider.valueChanged['int'].connect(self.progressBar.setValue)
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate


        self.groupBox.setTitle(_translate("QUICreator", "分组框"))
        self.lab.setText(_translate("QUICreator", "飞扬青云"))
        self.lineEdit.setText(_translate("QUICreator", "拿人钱财替人消灾,人生江湖如此,程序江湖亦如此."))
        self.rbtn1.setText(_translate("QUICreator", "单选框1"))
        self.rbtn2.setText(_translate("QUICreator", "单选框2"))
        self.ck1.setText(_translate("QUICreator", "复选框1"))
        self.ck2.setText(_translate("QUICreator", "复选框2"))
        self.ck3.setText(_translate("QUICreator", "复选框3"))
        self.btnInfo.setText(_translate("QUICreator", "信息框"))
        self.btnQuestion.setText(_translate("QUICreator", "提示框"))
        self.btnError.setText(_translate("QUICreator", "错误框"))
        self.btnInput.setText(_translate("QUICreator", "标准输入框"))
        self.btnInputPwd.setText(_translate("QUICreator", "密码输入框"))
        self.btnInputcbox.setText(_translate("QUICreator", "下拉输入框"))
        self.btnWidget.setText(_translate("QUICreator", "新窗体"))
        self.plainTextEdit.setPlainText(_translate("QUICreator", "每个人心中都有一段鲜不为人知的故事，\n"
                                                                 "如果不是某一天，\n"
                                                                 "某个不经意的回头一瞥，\n"
                                                                 "那段往事，\n"
                                                                 "就只能永远埋在记忆的最深处，\n"
                                                                 "那是回忆的尽头，\n"
                                                                 "可就无法避免那一触，\n"
                                                                 "无论你在上面用怎样淤厚的冷漠层层包裹，\n"
                                                                 "却总在瞬间崩溃。"))
        self.setTabText(self.indexOf(self.tab1), _translate("QUICreator", "客户资料"))
        self.setTabText(self.indexOf(self.tab2), _translate("QUICreator", "当前受理情况"))
        self.btn1.setText(_translate("QUICreator", "菜单1"))
        self.btn2.setText(_translate("QUICreator", "菜单2"))
        self.btn3.setText(_translate("QUICreator", "菜单3"))
        self.tbtn1.setText(_translate("QUICreator", "主界面"))
        self.tbtn2.setText(_translate("QUICreator", "警情查询"))
        self.tbtn3.setText(_translate("QUICreator", "系统设置"))
        self.lab1.setText(_translate("QUICreator", "欢迎使用软件"))
        self.lab2.setText(_translate("QUICreator", "当前用户【admin】"))
        self.lab3.setText(_translate("QUICreator", "已运行: 0天0时0分0秒"))
        self.lab4.setText(_translate("QUICreator", "当前时间: 2017年12月1日 12:00:00"))
        self.setTabText(self.indexOf(self.tab3), _translate("QUICreator", "客户回访记录"))
        self.setTabText(self.indexOf(self.tab4), _translate("QUICreator", "客户消费"))
        self.setTabText(self.indexOf(self.tab5), _translate("QUICreator", "预约情况"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab), _translate("QUICreator", "病例摘要"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_7), _translate("QUICreator", "效果预览"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_2), _translate("QUICreator", "效果预览"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_3), _translate("QUICreator", "效果预览"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_8), _translate("QUICreator", "效果预览"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_4), _translate("QUICreator", "效果预览"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_5), _translate("QUICreator", "效果预览"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_9), _translate("QUICreator", "效果预览"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_6), _translate("QUICreator", "效果预览"))
        self.setTabText(self.indexOf(self.tab6), _translate("QUICreator", "病例摘要"))
        self.setTabText(self.indexOf(self.tab7), _translate("QUICreator", "满意度调查"))
        self.setTabText(self.indexOf(self.tab8), _translate("QUICreator", "投诉处理"))
        self.btnUIDemo1.setText(_translate("QUICreator", "界面1"))
        self.btnUIDemo2.setText(_translate("QUICreator", "界面2"))
        self.btnUIDemo3.setText(_translate("QUICreator", "界面3"))
        self.btnUIDemo4.setText(_translate("QUICreator", "界面4"))
        self.btnUIDemo5.setText(_translate("QUICreator", "界面5"))
        self.btnUIDemo6.setText(_translate("QUICreator", "界面6"))
        self.btnUIDemo7.setText(_translate("QUICreator", "界面7"))
        self.btnUIDemo8.setText(_translate("QUICreator", "界面8"))
        self.setTabText(self.indexOf(self.tab9), _translate("QUICreator", "短信平台"))
        self.labCh1.setText(_translate("QUICreator", "通道1"))
        self.labCh2.setText(_translate("QUICreator", "通道2"))
        self.labCh3.setText(_translate("QUICreator", "通道3"))
        self.labCh4.setText(_translate("QUICreator", "通道4"))
        self.labCh5.setText(_translate("QUICreator", "通道5"))
        self.labCh6.setText(_translate("QUICreator", "通道6"))
        self.labCh7.setText(_translate("QUICreator", "通道7"))
        self.labCh8.setText(_translate("QUICreator", "通道8"))
        self.labCh9.setText(_translate("QUICreator", "通道9"))
        self.labCh10.setText(_translate("QUICreator", "通道10"))
        self.setTabText(self.indexOf(self.tab10), _translate("QUICreator", "统计报表"))



if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)

    ui = ouwai_table_tab_widget() #实例化一个（Ui创造者）类
    ui.show()#用这个类的setupUi方法创造一个窗体，相当于    用init函数在时候自动创建

    sys.exit(app.exec_())