# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\wwwww.000\PycharmProjects\pyqt5\new_jingmeijiemian\quicreator.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!
import sys
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_QUICreator(object):
    def setupUi(self, QUICreator):
        QUICreator.setObjectName("QUICreator")
        QUICreator.resize(850, 629)
        self.centralwidget = QtWidgets.QWidget(QUICreator)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.btnNew = QtWidgets.QPushButton(self.centralwidget)
        self.btnNew.setObjectName("btnNew")
        self.gridLayout.addWidget(self.btnNew, 0, 0, 1, 1)
        self.btnSave = QtWidgets.QPushButton(self.centralwidget)
        self.btnSave.setObjectName("btnSave")
        self.gridLayout.addWidget(self.btnSave, 0, 1, 1, 1)
        self.btnOpen = QtWidgets.QPushButton(self.centralwidget)
        self.btnOpen.setObjectName("btnOpen")
        self.gridLayout.addWidget(self.btnOpen, 1, 0, 1, 1)
        self.btnSaveOther = QtWidgets.QPushButton(self.centralwidget)
        self.btnSaveOther.setObjectName("btnSaveOther")
        self.gridLayout.addWidget(self.btnSaveOther, 1, 1, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.txtMain = QtWidgets.QTextEdit(self.centralwidget)
        self.txtMain.setObjectName("txtMain")
        self.gridLayout_7.addWidget(self.txtMain, 0, 1, 2, 1)
        self.frameColor = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameColor.sizePolicy().hasHeightForWidth())
        self.frameColor.setSizePolicy(sizePolicy)
        self.frameColor.setMinimumSize(QtCore.QSize(220, 0))
        self.frameColor.setMaximumSize(QtCore.QSize(220, 16777215))
        self.frameColor.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameColor.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameColor.setObjectName("frameColor")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frameColor)
        self.gridLayout_3.setContentsMargins(6, 6, 6, 6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.labTextColor = QtWidgets.QLabel(self.frameColor)
        self.labTextColor.setObjectName("labTextColor")
        self.gridLayout_3.addWidget(self.labTextColor, 0, 0, 1, 1)
        self.btnTextColor = QtWidgets.QPushButton(self.frameColor)
        self.btnTextColor.setText("")
        self.btnTextColor.setObjectName("btnTextColor")
        self.gridLayout_3.addWidget(self.btnTextColor, 0, 1, 1, 1)
        self.txtTextColor = QtWidgets.QLineEdit(self.frameColor)
        self.txtTextColor.setObjectName("txtTextColor")
        self.gridLayout_3.addWidget(self.txtTextColor, 0, 2, 1, 1)
        self.labPanelColor = QtWidgets.QLabel(self.frameColor)
        self.labPanelColor.setObjectName("labPanelColor")
        self.gridLayout_3.addWidget(self.labPanelColor, 1, 0, 1, 1)
        self.btnPanelColor = QtWidgets.QPushButton(self.frameColor)
        self.btnPanelColor.setText("")
        self.btnPanelColor.setObjectName("btnPanelColor")
        self.gridLayout_3.addWidget(self.btnPanelColor, 1, 1, 1, 1)
        self.txtPanelColor = QtWidgets.QLineEdit(self.frameColor)
        self.txtPanelColor.setObjectName("txtPanelColor")
        self.gridLayout_3.addWidget(self.txtPanelColor, 1, 2, 1, 1)
        self.labBorderColor = QtWidgets.QLabel(self.frameColor)
        self.labBorderColor.setObjectName("labBorderColor")
        self.gridLayout_3.addWidget(self.labBorderColor, 2, 0, 1, 1)
        self.btnBorderColor = QtWidgets.QPushButton(self.frameColor)
        self.btnBorderColor.setText("")
        self.btnBorderColor.setObjectName("btnBorderColor")
        self.gridLayout_3.addWidget(self.btnBorderColor, 2, 1, 1, 1)
        self.txtBorderColor = QtWidgets.QLineEdit(self.frameColor)
        self.txtBorderColor.setObjectName("txtBorderColor")
        self.gridLayout_3.addWidget(self.txtBorderColor, 2, 2, 1, 1)
        self.labNormalColorStart = QtWidgets.QLabel(self.frameColor)
        self.labNormalColorStart.setObjectName("labNormalColorStart")
        self.gridLayout_3.addWidget(self.labNormalColorStart, 3, 0, 1, 1)
        self.btnNormalColorStart = QtWidgets.QPushButton(self.frameColor)
        self.btnNormalColorStart.setText("")
        self.btnNormalColorStart.setObjectName("btnNormalColorStart")
        self.gridLayout_3.addWidget(self.btnNormalColorStart, 3, 1, 1, 1)
        self.txtNormalColorStart = QtWidgets.QLineEdit(self.frameColor)
        self.txtNormalColorStart.setObjectName("txtNormalColorStart")
        self.gridLayout_3.addWidget(self.txtNormalColorStart, 3, 2, 1, 1)
        self.labNormalColorEnd = QtWidgets.QLabel(self.frameColor)
        self.labNormalColorEnd.setObjectName("labNormalColorEnd")
        self.gridLayout_3.addWidget(self.labNormalColorEnd, 4, 0, 1, 1)
        self.btnNormalColorEnd = QtWidgets.QPushButton(self.frameColor)
        self.btnNormalColorEnd.setText("")
        self.btnNormalColorEnd.setObjectName("btnNormalColorEnd")
        self.gridLayout_3.addWidget(self.btnNormalColorEnd, 4, 1, 1, 1)
        self.txtNormalColorEnd = QtWidgets.QLineEdit(self.frameColor)
        self.txtNormalColorEnd.setObjectName("txtNormalColorEnd")
        self.gridLayout_3.addWidget(self.txtNormalColorEnd, 4, 2, 1, 1)
        self.labDarkColorStart = QtWidgets.QLabel(self.frameColor)
        self.labDarkColorStart.setObjectName("labDarkColorStart")
        self.gridLayout_3.addWidget(self.labDarkColorStart, 5, 0, 1, 1)
        self.btnDarkColorStart = QtWidgets.QPushButton(self.frameColor)
        self.btnDarkColorStart.setText("")
        self.btnDarkColorStart.setObjectName("btnDarkColorStart")
        self.gridLayout_3.addWidget(self.btnDarkColorStart, 5, 1, 1, 1)
        self.txtDarkColorStart = QtWidgets.QLineEdit(self.frameColor)
        self.txtDarkColorStart.setObjectName("txtDarkColorStart")
        self.gridLayout_3.addWidget(self.txtDarkColorStart, 5, 2, 1, 1)
        self.labDarkColorEnd = QtWidgets.QLabel(self.frameColor)
        self.labDarkColorEnd.setObjectName("labDarkColorEnd")
        self.gridLayout_3.addWidget(self.labDarkColorEnd, 6, 0, 1, 1)
        self.btnDarkColorEnd = QtWidgets.QPushButton(self.frameColor)
        self.btnDarkColorEnd.setText("")
        self.btnDarkColorEnd.setObjectName("btnDarkColorEnd")
        self.gridLayout_3.addWidget(self.btnDarkColorEnd, 6, 1, 1, 1)
        self.txtDarkColorEnd = QtWidgets.QLineEdit(self.frameColor)
        self.txtDarkColorEnd.setObjectName("txtDarkColorEnd")
        self.gridLayout_3.addWidget(self.txtDarkColorEnd, 6, 2, 1, 1)
        self.labHighColor = QtWidgets.QLabel(self.frameColor)
        self.labHighColor.setObjectName("labHighColor")
        self.gridLayout_3.addWidget(self.labHighColor, 7, 0, 1, 1)
        self.btnHighColor = QtWidgets.QPushButton(self.frameColor)
        self.btnHighColor.setText("")
        self.btnHighColor.setObjectName("btnHighColor")
        self.gridLayout_3.addWidget(self.btnHighColor, 7, 1, 1, 1)
        self.txtHighColor = QtWidgets.QLineEdit(self.frameColor)
        self.txtHighColor.setObjectName("txtHighColor")
        self.gridLayout_3.addWidget(self.txtHighColor, 7, 2, 1, 1)
        self.gridLayout_7.addWidget(self.frameColor, 1, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab1 = QtWidgets.QWidget()
        self.tab1.setObjectName("tab1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.tab1)
        self.groupBox.setStyleSheet("")
        self.groupBox.setCheckable(True)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lab = QtWidgets.QLabel(self.groupBox)
        self.lab.setAlignment(QtCore.Qt.AlignCenter)
        self.lab.setObjectName("lab")
        self.gridLayout_2.addWidget(self.lab, 0, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_2.addWidget(self.lineEdit, 0, 1, 1, 6)
        self.rbtn1 = QtWidgets.QRadioButton(self.groupBox)
        self.rbtn1.setObjectName("rbtn1")
        self.gridLayout_2.addWidget(self.rbtn1, 1, 0, 1, 1)
        self.rbtn2 = QtWidgets.QRadioButton(self.groupBox)
        self.rbtn2.setObjectName("rbtn2")
        self.gridLayout_2.addWidget(self.rbtn2, 1, 1, 1, 1)
        self.ck1 = QtWidgets.QCheckBox(self.groupBox)
        self.ck1.setObjectName("ck1")
        self.gridLayout_2.addWidget(self.ck1, 1, 2, 1, 1)
        self.ck2 = QtWidgets.QCheckBox(self.groupBox)
        self.ck2.setChecked(False)
        self.ck2.setObjectName("ck2")
        self.gridLayout_2.addWidget(self.ck2, 1, 3, 1, 1)
        self.ck3 = QtWidgets.QCheckBox(self.groupBox)
        self.ck3.setObjectName("ck3")
        self.gridLayout_2.addWidget(self.ck3, 1, 4, 1, 1)
        self.cbox1 = QtWidgets.QComboBox(self.groupBox)
        self.cbox1.setMaximumSize(QtCore.QSize(16777215, 28))
        self.cbox1.setObjectName("cbox1")
        self.gridLayout_2.addWidget(self.cbox1, 1, 5, 1, 1)
        self.cbox2 = QtWidgets.QComboBox(self.groupBox)
        self.cbox2.setMaximumSize(QtCore.QSize(16777215, 28))
        self.cbox2.setObjectName("cbox2")
        self.gridLayout_2.addWidget(self.cbox2, 1, 6, 1, 1)
        self.btnInfo = QtWidgets.QPushButton(self.groupBox)
        self.btnInfo.setObjectName("btnInfo")
        self.gridLayout_2.addWidget(self.btnInfo, 2, 0, 1, 1)
        self.btnQuestion = QtWidgets.QPushButton(self.groupBox)
        self.btnQuestion.setObjectName("btnQuestion")
        self.gridLayout_2.addWidget(self.btnQuestion, 2, 1, 1, 1)
        self.btnError = QtWidgets.QPushButton(self.groupBox)
        self.btnError.setObjectName("btnError")
        self.gridLayout_2.addWidget(self.btnError, 2, 2, 1, 1)
        self.btnInput = QtWidgets.QPushButton(self.groupBox)
        self.btnInput.setObjectName("btnInput")
        self.gridLayout_2.addWidget(self.btnInput, 2, 3, 1, 1)
        self.btnInputPwd = QtWidgets.QPushButton(self.groupBox)
        self.btnInputPwd.setObjectName("btnInputPwd")
        self.gridLayout_2.addWidget(self.btnInputPwd, 2, 4, 1, 1)
        self.btnInputcbox = QtWidgets.QPushButton(self.groupBox)
        self.btnInputcbox.setObjectName("btnInputcbox")
        self.gridLayout_2.addWidget(self.btnInputcbox, 2, 5, 1, 1)
        self.btnWidget = QtWidgets.QPushButton(self.groupBox)
        self.btnWidget.setObjectName("btnWidget")
        self.gridLayout_2.addWidget(self.btnWidget, 2, 6, 1, 1)
        self.spinBox = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout_2.addWidget(self.spinBox, 3, 0, 1, 1)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.gridLayout_2.addWidget(self.doubleSpinBox, 3, 1, 1, 1)
        self.timeEdit = QtWidgets.QTimeEdit(self.groupBox)
        self.timeEdit.setObjectName("timeEdit")
        self.gridLayout_2.addWidget(self.timeEdit, 3, 2, 1, 1)
        self.dateEdit = QtWidgets.QDateEdit(self.groupBox)
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName("dateEdit")
        self.gridLayout_2.addWidget(self.dateEdit, 3, 3, 1, 2)
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.groupBox)
        self.dateTimeEdit.setCalendarPopup(True)
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.gridLayout_2.addWidget(self.dateTimeEdit, 3, 5, 1, 2)
        self.horizontalSlider = QtWidgets.QSlider(self.groupBox)
        self.horizontalSlider.setMaximum(100)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.gridLayout_2.addWidget(self.horizontalSlider, 4, 0, 1, 3)
        self.progressBar = QtWidgets.QProgressBar(self.groupBox)
        self.progressBar.setMaximumSize(QtCore.QSize(16777215, 18))
        self.progressBar.setObjectName("progressBar")
        self.gridLayout_2.addWidget(self.progressBar, 4, 3, 1, 4)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.groupBox)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.gridLayout_2.addWidget(self.plainTextEdit, 5, 0, 1, 7)
        self.verticalLayout.addWidget(self.groupBox)
        self.tabWidget.addTab(self.tab1, "")
        self.tab2 = QtWidgets.QWidget()
        self.tab2.setObjectName("tab2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.tab2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tableWidget = QtWidgets.QTableWidget(self.tab2)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.horizontalLayout.addWidget(self.tableWidget)
        self.tabWidget.addTab(self.tab2, "")
        self.tab3 = QtWidgets.QWidget()
        self.tab3.setObjectName("tab3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.tab3)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.widgetLeft = QtWidgets.QWidget(self.tab3)
        self.widgetLeft.setMinimumSize(QtCore.QSize(80, 0))
        self.widgetLeft.setObjectName("widgetLeft")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widgetLeft)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btn1 = QtWidgets.QPushButton(self.widgetLeft)
        self.btn1.setChecked(False)
        self.btn1.setObjectName("btn1")
        self.verticalLayout_2.addWidget(self.btn1)
        self.btn2 = QtWidgets.QPushButton(self.widgetLeft)
        self.btn2.setObjectName("btn2")
        self.verticalLayout_2.addWidget(self.btn2)
        self.btn3 = QtWidgets.QPushButton(self.widgetLeft)
        self.btn3.setObjectName("btn3")
        self.verticalLayout_2.addWidget(self.btn3)
        spacerItem = QtWidgets.QSpacerItem(20, 222, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout_7.addWidget(self.widgetLeft)
        self.stackedWidget = QtWidgets.QStackedWidget(self.tab3)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page1 = QtWidgets.QWidget()
        self.page1.setObjectName("page1")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.page1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widgetTop = QtWidgets.QWidget(self.page1)
        self.widgetTop.setObjectName("widgetTop")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widgetTop)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tbtn1 = QtWidgets.QToolButton(self.widgetTop)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbtn1.sizePolicy().hasHeightForWidth())
        self.tbtn1.setSizePolicy(sizePolicy)
        self.tbtn1.setObjectName("tbtn1")
        self.horizontalLayout_2.addWidget(self.tbtn1)
        self.tbtn2 = QtWidgets.QToolButton(self.widgetTop)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbtn2.sizePolicy().hasHeightForWidth())
        self.tbtn2.setSizePolicy(sizePolicy)
        self.tbtn2.setObjectName("tbtn2")
        self.horizontalLayout_2.addWidget(self.tbtn2)
        self.tbtn3 = QtWidgets.QToolButton(self.widgetTop)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbtn3.sizePolicy().hasHeightForWidth())
        self.tbtn3.setSizePolicy(sizePolicy)
        self.tbtn3.setObjectName("tbtn3")
        self.horizontalLayout_2.addWidget(self.tbtn3)
        self.verticalLayout_4.addWidget(self.widgetTop)
        self.widget = QtWidgets.QWidget(self.page1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.verticalLayout_4.addWidget(self.widget)
        self.widgetBottom = QtWidgets.QWidget(self.page1)
        self.widgetBottom.setMaximumSize(QtCore.QSize(16777215, 30))
        self.widgetBottom.setObjectName("widgetBottom")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widgetBottom)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lab1 = QtWidgets.QLabel(self.widgetBottom)
        self.lab1.setObjectName("lab1")
        self.horizontalLayout_3.addWidget(self.lab1)
        self.line1 = QtWidgets.QFrame(self.widgetBottom)
        self.line1.setMaximumSize(QtCore.QSize(1, 16777215))
        self.line1.setFrameShape(QtWidgets.QFrame.VLine)
        self.line1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line1.setObjectName("line1")
        self.horizontalLayout_3.addWidget(self.line1)
        self.lab2 = QtWidgets.QLabel(self.widgetBottom)
        self.lab2.setObjectName("lab2")
        self.horizontalLayout_3.addWidget(self.lab2)
        self.line2 = QtWidgets.QFrame(self.widgetBottom)
        self.line2.setMaximumSize(QtCore.QSize(1, 16777215))
        self.line2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line2.setObjectName("line2")
        self.horizontalLayout_3.addWidget(self.line2)
        self.lab3 = QtWidgets.QLabel(self.widgetBottom)
        self.lab3.setObjectName("lab3")
        self.horizontalLayout_3.addWidget(self.lab3)
        self.line3 = QtWidgets.QFrame(self.widgetBottom)
        self.line3.setMaximumSize(QtCore.QSize(1, 16777215))
        self.line3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line3.setObjectName("line3")
        self.horizontalLayout_3.addWidget(self.line3)
        self.lab4 = QtWidgets.QLabel(self.widgetBottom)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lab4.sizePolicy().hasHeightForWidth())
        self.lab4.setSizePolicy(sizePolicy)
        self.lab4.setObjectName("lab4")
        self.horizontalLayout_3.addWidget(self.lab4)
        self.verticalLayout_4.addWidget(self.widgetBottom)
        self.stackedWidget.addWidget(self.page1)
        self.page2 = QtWidgets.QWidget()
        self.page2.setObjectName("page2")
        self.stackedWidget.addWidget(self.page2)
        self.page3 = QtWidgets.QWidget()
        self.page3.setObjectName("page3")
        self.stackedWidget.addWidget(self.page3)
        self.horizontalLayout_7.addWidget(self.stackedWidget)
        self.verticalSlider = QtWidgets.QSlider(self.tab3)
        self.verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider.setObjectName("verticalSlider")
        self.horizontalLayout_7.addWidget(self.verticalSlider)
        self.verticalScrollBar = QtWidgets.QScrollBar(self.tab3)
        self.verticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")
        self.horizontalLayout_7.addWidget(self.verticalScrollBar)
        self.tabWidget.addTab(self.tab3, "")
        self.tab4 = QtWidgets.QWidget()
        self.tab4.setObjectName("tab4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.tab4)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.treeWidget = QtWidgets.QTreeWidget(self.tab4)
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setText(0, "1")
        self.horizontalLayout_4.addWidget(self.treeWidget)
        self.listWidget = QtWidgets.QListWidget(self.tab4)
        self.listWidget.setObjectName("listWidget")
        self.horizontalLayout_4.addWidget(self.listWidget)
        self.tabWidget.addTab(self.tab4, "")
        self.tab5 = QtWidgets.QWidget()
        self.tab5.setObjectName("tab5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.tab5)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.calendarWidget1 = QtWidgets.QCalendarWidget(self.tab5)
        self.calendarWidget1.setObjectName("calendarWidget1")
        self.horizontalLayout_5.addWidget(self.calendarWidget1)
        self.calendarWidget2 = QtWidgets.QCalendarWidget(self.tab5)
        self.calendarWidget2.setGridVisible(True)
        self.calendarWidget2.setObjectName("calendarWidget2")
        self.horizontalLayout_5.addWidget(self.calendarWidget2)
        self.tabWidget.addTab(self.tab5, "")
        self.tab6 = QtWidgets.QWidget()
        self.tab6.setObjectName("tab6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.tab6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab6)
        self.tabWidget_2.setTabPosition(QtWidgets.QTabWidget.West)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tabWidget_2.addTab(self.tab, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.tabWidget_2.addTab(self.tab_7, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget_2.addTab(self.tab_2, "")
        self.horizontalLayout_6.addWidget(self.tabWidget_2)
        self.tabWidget_3 = QtWidgets.QTabWidget(self.tab6)
        self.tabWidget_3.setTabPosition(QtWidgets.QTabWidget.South)
        self.tabWidget_3.setObjectName("tabWidget_3")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget_3.addTab(self.tab_3, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.tabWidget_3.addTab(self.tab_8, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabWidget_3.addTab(self.tab_4, "")
        self.horizontalLayout_6.addWidget(self.tabWidget_3)
        self.tabWidget_4 = QtWidgets.QTabWidget(self.tab6)
        self.tabWidget_4.setTabPosition(QtWidgets.QTabWidget.East)
        self.tabWidget_4.setObjectName("tabWidget_4")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.tabWidget_4.addTab(self.tab_5, "")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.tabWidget_4.addTab(self.tab_9, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.tabWidget_4.addTab(self.tab_6, "")
        self.horizontalLayout_6.addWidget(self.tabWidget_4)
        self.tabWidget.addTab(self.tab6, "")
        self.tab7 = QtWidgets.QWidget()
        self.tab7.setObjectName("tab7")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab7)
        self.verticalLayout_3.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widgetPanel = QtWidgets.QWidget(self.tab7)
        self.widgetPanel.setObjectName("widgetPanel")
        self.verticalLayout_3.addWidget(self.widgetPanel)
        self.tabWidget.addTab(self.tab7, "")
        self.tab8 = QtWidgets.QWidget()
        self.tab8.setObjectName("tab8")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab8)
        self.verticalLayout_5.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.widgetFontPanel = QtWidgets.QWidget(self.tab8)
        self.widgetFontPanel.setObjectName("widgetFontPanel")
        self.verticalLayout_5.addWidget(self.widgetFontPanel)
        self.tabWidget.addTab(self.tab8, "")
        self.tab9 = QtWidgets.QWidget()
        self.tab9.setObjectName("tab9")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab9)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.btnUIDemo1 = QtWidgets.QPushButton(self.tab9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnUIDemo1.sizePolicy().hasHeightForWidth())
        self.btnUIDemo1.setSizePolicy(sizePolicy)
        self.btnUIDemo1.setObjectName("btnUIDemo1")
        self.gridLayout_4.addWidget(self.btnUIDemo1, 0, 0, 1, 1)
        self.btnUIDemo2 = QtWidgets.QPushButton(self.tab9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnUIDemo2.sizePolicy().hasHeightForWidth())
        self.btnUIDemo2.setSizePolicy(sizePolicy)
        self.btnUIDemo2.setObjectName("btnUIDemo2")
        self.gridLayout_4.addWidget(self.btnUIDemo2, 0, 1, 1, 1)
        self.btnUIDemo3 = QtWidgets.QPushButton(self.tab9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnUIDemo3.sizePolicy().hasHeightForWidth())
        self.btnUIDemo3.setSizePolicy(sizePolicy)
        self.btnUIDemo3.setObjectName("btnUIDemo3")
        self.gridLayout_4.addWidget(self.btnUIDemo3, 0, 2, 1, 1)
        self.btnUIDemo4 = QtWidgets.QPushButton(self.tab9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnUIDemo4.sizePolicy().hasHeightForWidth())
        self.btnUIDemo4.setSizePolicy(sizePolicy)
        self.btnUIDemo4.setObjectName("btnUIDemo4")
        self.gridLayout_4.addWidget(self.btnUIDemo4, 0, 3, 1, 1)
        self.btnUIDemo5 = QtWidgets.QPushButton(self.tab9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnUIDemo5.sizePolicy().hasHeightForWidth())
        self.btnUIDemo5.setSizePolicy(sizePolicy)
        self.btnUIDemo5.setObjectName("btnUIDemo5")
        self.gridLayout_4.addWidget(self.btnUIDemo5, 1, 0, 1, 1)
        self.btnUIDemo6 = QtWidgets.QPushButton(self.tab9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnUIDemo6.sizePolicy().hasHeightForWidth())
        self.btnUIDemo6.setSizePolicy(sizePolicy)
        self.btnUIDemo6.setObjectName("btnUIDemo6")
        self.gridLayout_4.addWidget(self.btnUIDemo6, 1, 1, 1, 1)
        self.btnUIDemo7 = QtWidgets.QPushButton(self.tab9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnUIDemo7.sizePolicy().hasHeightForWidth())
        self.btnUIDemo7.setSizePolicy(sizePolicy)
        self.btnUIDemo7.setObjectName("btnUIDemo7")
        self.gridLayout_4.addWidget(self.btnUIDemo7, 1, 2, 1, 1)
        self.btnUIDemo8 = QtWidgets.QPushButton(self.tab9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnUIDemo8.sizePolicy().hasHeightForWidth())
        self.btnUIDemo8.setSizePolicy(sizePolicy)
        self.btnUIDemo8.setObjectName("btnUIDemo8")
        self.gridLayout_4.addWidget(self.btnUIDemo8, 1, 3, 1, 1)
        self.tabWidget.addTab(self.tab9, "")
        self.tab10 = QtWidgets.QWidget()
        self.tab10.setObjectName("tab10")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab10)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.widgetVideo = QtWidgets.QWidget(self.tab10)
        self.widgetVideo.setObjectName("widgetVideo")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.widgetVideo)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.labCh1 = QtWidgets.QLabel(self.widgetVideo)
        self.labCh1.setAlignment(QtCore.Qt.AlignCenter)
        self.labCh1.setObjectName("labCh1")
        self.gridLayout_5.addWidget(self.labCh1, 0, 0, 1, 1)
        self.labCh2 = QtWidgets.QLabel(self.widgetVideo)
        self.labCh2.setAlignment(QtCore.Qt.AlignCenter)
        self.labCh2.setObjectName("labCh2")
        self.gridLayout_5.addWidget(self.labCh2, 0, 1, 1, 1)
        self.labCh3 = QtWidgets.QLabel(self.widgetVideo)
        self.labCh3.setAlignment(QtCore.Qt.AlignCenter)
        self.labCh3.setObjectName("labCh3")
        self.gridLayout_5.addWidget(self.labCh3, 0, 2, 1, 1)
        self.labCh4 = QtWidgets.QLabel(self.widgetVideo)
        self.labCh4.setAlignment(QtCore.Qt.AlignCenter)
        self.labCh4.setObjectName("labCh4")
        self.gridLayout_5.addWidget(self.labCh4, 0, 3, 1, 1)
        self.labCh5 = QtWidgets.QLabel(self.widgetVideo)
        self.labCh5.setAlignment(QtCore.Qt.AlignCenter)
        self.labCh5.setObjectName("labCh5")
        self.gridLayout_5.addWidget(self.labCh5, 0, 4, 1, 1)
        self.labCh6 = QtWidgets.QLabel(self.widgetVideo)
        self.labCh6.setAlignment(QtCore.Qt.AlignCenter)
        self.labCh6.setObjectName("labCh6")
        self.gridLayout_5.addWidget(self.labCh6, 1, 0, 1, 1)
        self.labCh7 = QtWidgets.QLabel(self.widgetVideo)
        self.labCh7.setAlignment(QtCore.Qt.AlignCenter)
        self.labCh7.setObjectName("labCh7")
        self.gridLayout_5.addWidget(self.labCh7, 1, 1, 1, 1)
        self.labCh8 = QtWidgets.QLabel(self.widgetVideo)
        self.labCh8.setAlignment(QtCore.Qt.AlignCenter)
        self.labCh8.setObjectName("labCh8")
        self.gridLayout_5.addWidget(self.labCh8, 1, 2, 1, 1)
        self.labCh9 = QtWidgets.QLabel(self.widgetVideo)
        self.labCh9.setAlignment(QtCore.Qt.AlignCenter)
        self.labCh9.setObjectName("labCh9")
        self.gridLayout_5.addWidget(self.labCh9, 1, 3, 1, 1)
        self.labCh10 = QtWidgets.QLabel(self.widgetVideo)
        self.labCh10.setAlignment(QtCore.Qt.AlignCenter)
        self.labCh10.setObjectName("labCh10")
        self.gridLayout_5.addWidget(self.labCh10, 1, 4, 1, 1)
        self.verticalLayout_6.addWidget(self.widgetVideo)
        self.tabWidget.addTab(self.tab10, "")
        self.gridLayout_7.addWidget(self.tabWidget, 2, 0, 1, 2)
        QUICreator.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(QUICreator)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 850, 23))
        self.menubar.setObjectName("menubar")
        self.menu_F = QtWidgets.QMenu(self.menubar)
        self.menu_F.setObjectName("menu_F")
        self.menu_E = QtWidgets.QMenu(self.menubar)
        self.menu_E.setObjectName("menu_E")
        self.menu_B = QtWidgets.QMenu(self.menubar)
        self.menu_B.setObjectName("menu_B")
        self.menu_H = QtWidgets.QMenu(self.menubar)
        self.menu_H.setObjectName("menu_H")
        QUICreator.setMenuBar(self.menubar)
        self.action = QtWidgets.QAction(QUICreator)
        self.action.setObjectName("action")
        self.action_O = QtWidgets.QAction(QUICreator)
        self.action_O.setObjectName("action_O")
        self.action_S = QtWidgets.QAction(QUICreator)
        self.action_S.setObjectName("action_S")
        self.action_C = QtWidgets.QAction(QUICreator)
        self.action_C.setObjectName("action_C")
        self.action_X = QtWidgets.QAction(QUICreator)
        self.action_X.setObjectName("action_X")
        self.action_C_2 = QtWidgets.QAction(QUICreator)
        self.action_C_2.setObjectName("action_C_2")
        self.action_V = QtWidgets.QAction(QUICreator)
        self.action_V.setObjectName("action_V")
        self.actionGouj = QtWidgets.QAction(QUICreator)
        self.actionGouj.setObjectName("actionGouj")
        self.action_T = QtWidgets.QAction(QUICreator)
        self.action_T.setObjectName("action_T")
        self.action_A = QtWidgets.QAction(QUICreator)
        self.action_A.setObjectName("action_A")
        self.menu_F.addAction(self.action)
        self.menu_F.addAction(self.action_O)
        self.menu_F.addSeparator()
        self.menu_F.addAction(self.action_S)
        self.menu_F.addAction(self.action_C)
        self.menu_E.addAction(self.action_X)
        self.menu_E.addAction(self.action_C_2)
        self.menu_E.addAction(self.action_V)
        self.menu_B.addAction(self.actionGouj)
        self.menu_H.addAction(self.action_T)
        self.menu_H.addAction(self.action_A)
        self.menubar.addAction(self.menu_F.menuAction())
        self.menubar.addAction(self.menu_E.menuAction())
        self.menubar.addAction(self.menu_B.menuAction())
        self.menubar.addAction(self.menu_H.menuAction())

        self.retranslateUi(QUICreator)
        self.tabWidget.setCurrentIndex(0)
        self.stackedWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(2)
        self.tabWidget_3.setCurrentIndex(0)
        self.tabWidget_4.setCurrentIndex(2)
        self.horizontalSlider.valueChanged['int'].connect(self.progressBar.setValue)
        QtCore.QMetaObject.connectSlotsByName(QUICreator)

    def retranslateUi(self, QUICreator):
        _translate = QtCore.QCoreApplication.translate
        QUICreator.setWindowTitle(_translate("QUICreator", "MainWindow"))
        self.btnNew.setText(_translate("QUICreator", "新建"))
        self.btnSave.setText(_translate("QUICreator", "保存"))
        self.btnOpen.setText(_translate("QUICreator", "打开"))
        self.btnSaveOther.setText(_translate("QUICreator", "另存为"))
        self.labTextColor.setText(_translate("QUICreator", "字体颜色"))
        self.labPanelColor.setText(_translate("QUICreator", "面板背景"))
        self.labBorderColor.setText(_translate("QUICreator", "边框颜色"))
        self.labNormalColorStart.setText(_translate("QUICreator", "普通渐变开始"))
        self.labNormalColorEnd.setText(_translate("QUICreator", "普通渐变结束"))
        self.labDarkColorStart.setText(_translate("QUICreator", "加深渐变开始"))
        self.labDarkColorEnd.setText(_translate("QUICreator", "加深渐变结束"))
        self.labHighColor.setText(_translate("QUICreator", "边缘高亮颜色"))
        self.groupBox.setTitle(_translate("QUICreator", "分组框"))
        self.lab.setText(_translate("QUICreator", "飞扬青云"))
        self.lineEdit.setText(_translate("QUICreator", "拿人钱财替人消灾,人生江湖如此,程序江湖亦如此."))
        self.rbtn1.setText(_translate("QUICreator", "单选框1"))
        self.rbtn2.setText(_translate("QUICreator", "单选框2"))
        self.ck1.setText(_translate("QUICreator", "复选框1"))
        self.ck2.setText(_translate("QUICreator", "复选框2"))
        self.ck3.setText(_translate("QUICreator", "复选框3"))
        self.btnInfo.setText(_translate("QUICreator", "信息框"))
        self.btnQuestion.setText(_translate("QUICreator", "提示框"))
        self.btnError.setText(_translate("QUICreator", "错误框"))
        self.btnInput.setText(_translate("QUICreator", "标准输入框"))
        self.btnInputPwd.setText(_translate("QUICreator", "密码输入框"))
        self.btnInputcbox.setText(_translate("QUICreator", "下拉输入框"))
        self.btnWidget.setText(_translate("QUICreator", "新窗体"))
        self.plainTextEdit.setPlainText(_translate("QUICreator", "每个人心中都有一段鲜不为人知的故事，\n"
"如果不是某一天，\n"
"某个不经意的回头一瞥，\n"
"那段往事，\n"
"就只能永远埋在记忆的最深处，\n"
"那是回忆的尽头，\n"
"可就无法避免那一触，\n"
"无论你在上面用怎样淤厚的冷漠层层包裹，\n"
"却总在瞬间崩溃。"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab1), _translate("QUICreator", "常用组件"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab2), _translate("QUICreator", "表格数据"))
        self.btn1.setText(_translate("QUICreator", "菜单1"))
        self.btn2.setText(_translate("QUICreator", "菜单2"))
        self.btn3.setText(_translate("QUICreator", "菜单3"))
        self.tbtn1.setText(_translate("QUICreator", "主界面"))
        self.tbtn2.setText(_translate("QUICreator", "警情查询"))
        self.tbtn3.setText(_translate("QUICreator", "系统设置"))
        self.lab1.setText(_translate("QUICreator", "欢迎使用软件"))
        self.lab2.setText(_translate("QUICreator", "当前用户【admin】"))
        self.lab3.setText(_translate("QUICreator", "已运行: 0天0时0分0秒"))
        self.lab4.setText(_translate("QUICreator", "当前时间: 2017年12月1日 12:00:00"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab3), _translate("QUICreator", "导航界面"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab4), _translate("QUICreator", "树状列表"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab5), _translate("QUICreator", "日历效果"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab), _translate("QUICreator", "效果预览"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_7), _translate("QUICreator", "效果预览"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_2), _translate("QUICreator", "效果预览"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_3), _translate("QUICreator", "效果预览"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_8), _translate("QUICreator", "效果预览"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_4), _translate("QUICreator", "效果预览"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_5), _translate("QUICreator", "效果预览"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_9), _translate("QUICreator", "效果预览"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_6), _translate("QUICreator", "效果预览"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab6), _translate("QUICreator", "tab选项卡"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab7), _translate("QUICreator", "设备面板"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab8), _translate("QUICreator", "图形字体"))
        self.btnUIDemo1.setText(_translate("QUICreator", "界面1"))
        self.btnUIDemo2.setText(_translate("QUICreator", "界面2"))
        self.btnUIDemo3.setText(_translate("QUICreator", "界面3"))
        self.btnUIDemo4.setText(_translate("QUICreator", "界面4"))
        self.btnUIDemo5.setText(_translate("QUICreator", "界面5"))
        self.btnUIDemo6.setText(_translate("QUICreator", "界面6"))
        self.btnUIDemo7.setText(_translate("QUICreator", "界面7"))
        self.btnUIDemo8.setText(_translate("QUICreator", "界面8"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab9), _translate("QUICreator", "UI界面"))
        self.labCh1.setText(_translate("QUICreator", "通道1"))
        self.labCh2.setText(_translate("QUICreator", "通道2"))
        self.labCh3.setText(_translate("QUICreator", "通道3"))
        self.labCh4.setText(_translate("QUICreator", "通道4"))
        self.labCh5.setText(_translate("QUICreator", "通道5"))
        self.labCh6.setText(_translate("QUICreator", "通道6"))
        self.labCh7.setText(_translate("QUICreator", "通道7"))
        self.labCh8.setText(_translate("QUICreator", "通道8"))
        self.labCh9.setText(_translate("QUICreator", "通道9"))
        self.labCh10.setText(_translate("QUICreator", "通道10"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab10), _translate("QUICreator", "视频监控"))
        self.menu_F.setTitle(_translate("QUICreator", "文件(&F)"))
        self.menu_E.setTitle(_translate("QUICreator", "编辑(&E)"))
        self.menu_B.setTitle(_translate("QUICreator", "构建(&B)"))
        self.menu_H.setTitle(_translate("QUICreator", "帮助(&H)"))
        self.action.setText(_translate("QUICreator", "新建文件(&N)"))
        self.action_O.setText(_translate("QUICreator", "打开文件(&O)"))
        self.action_S.setText(_translate("QUICreator", "保存文件(&S) "))
        self.action_C.setText(_translate("QUICreator", "关闭退出(&C)"))
        self.action_X.setText(_translate("QUICreator", "剪切(&X) "))
        self.action_C_2.setText(_translate("QUICreator", "复制(&C)"))
        self.action_V.setText(_translate("QUICreator", "粘贴(&V)"))
        self.actionGouj.setText(_translate("QUICreator", "构建项目(&B)"))
        self.action_T.setText(_translate("QUICreator", "帮助文档(&T)"))
        self.action_A.setText(_translate("QUICreator", "关于(&A)"))

if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()#创建一个空主窗体
    ui = Ui_QUICreator() #实例化一个（Ui创造者）类
    ui.setupUi(mainWindow)#用这个类的setupUi方法创造一个窗体，相当于    用init函数在时候自动创建
    mainWindow.show() #窗体显示
    sys.exit(app.exec_())