# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\wwwww.000\PycharmProjects\pyqt5\new_jingmeijiemian\表格.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(884, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 80, 812, 100))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.comboBox = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout.addWidget(self.comboBox, 0, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 0, 4, 1, 1)
        self.comboBox_12 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_12.setObjectName("comboBox_12")
        self.gridLayout.addWidget(self.comboBox_12, 3, 5, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.comboBox_3 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_3.setObjectName("comboBox_3")
        self.gridLayout.addWidget(self.comboBox_3, 2, 1, 1, 1)
        self.comboBox_16 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_16.setObjectName("comboBox_16")
        self.gridLayout.addWidget(self.comboBox_16, 3, 7, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 1, 8, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.comboBox_13 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_13.setObjectName("comboBox_13")
        self.gridLayout.addWidget(self.comboBox_13, 0, 7, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 3, 6, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 1, 6, 1, 1)
        self.comboBox_8 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_8.setObjectName("comboBox_8")
        self.gridLayout.addWidget(self.comboBox_8, 3, 3, 1, 1)
        self.comboBox_4 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_4.setObjectName("comboBox_4")
        self.gridLayout.addWidget(self.comboBox_4, 3, 1, 1, 1)
        self.comboBox_20 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_20.setObjectName("comboBox_20")
        self.gridLayout.addWidget(self.comboBox_20, 3, 9, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 2, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 1, 2, 1, 1)
        self.comboBox_6 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_6.setObjectName("comboBox_6")
        self.gridLayout.addWidget(self.comboBox_6, 1, 3, 1, 1)
        self.comboBox_5 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_5.setObjectName("comboBox_5")
        self.gridLayout.addWidget(self.comboBox_5, 0, 3, 1, 1)
        self.comboBox_18 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_18.setObjectName("comboBox_18")
        self.gridLayout.addWidget(self.comboBox_18, 1, 9, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 2, 4, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 2, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 0, 8, 1, 1)
        self.comboBox_11 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_11.setObjectName("comboBox_11")
        self.gridLayout.addWidget(self.comboBox_11, 2, 5, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_20.setObjectName("label_20")
        self.gridLayout.addWidget(self.label_20, 3, 8, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_23.setObjectName("label_23")
        self.gridLayout.addWidget(self.label_23, 2, 10, 1, 1)
        self.comboBox_15 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_15.setObjectName("comboBox_15")
        self.gridLayout.addWidget(self.comboBox_15, 2, 7, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_21.setObjectName("label_21")
        self.gridLayout.addWidget(self.label_21, 0, 10, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_22.setObjectName("label_22")
        self.gridLayout.addWidget(self.label_22, 1, 10, 1, 1)
        self.comboBox_17 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_17.setObjectName("comboBox_17")
        self.gridLayout.addWidget(self.comboBox_17, 0, 9, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 2, 6, 1, 1)
        self.comboBox_14 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_14.setObjectName("comboBox_14")
        self.gridLayout.addWidget(self.comboBox_14, 1, 7, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 1, 4, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 3, 2, 1, 1)
        self.comboBox_10 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_10.setObjectName("comboBox_10")
        self.gridLayout.addWidget(self.comboBox_10, 1, 5, 1, 1)
        self.comboBox_19 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_19.setObjectName("comboBox_19")
        self.gridLayout.addWidget(self.comboBox_19, 2, 9, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_2.setObjectName("comboBox_2")
        self.gridLayout.addWidget(self.comboBox_2, 1, 1, 1, 1)
        self.comboBox_9 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_9.setObjectName("comboBox_9")
        self.gridLayout.addWidget(self.comboBox_9, 0, 5, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.comboBox_7 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_7.setObjectName("comboBox_7")
        self.gridLayout.addWidget(self.comboBox_7, 2, 3, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_24.setObjectName("label_24")
        self.gridLayout.addWidget(self.label_24, 3, 10, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_19.setObjectName("label_19")
        self.gridLayout.addWidget(self.label_19, 2, 8, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 3, 4, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 0, 6, 1, 1)
        self.comboBox_21 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_21.setObjectName("comboBox_21")
        self.gridLayout.addWidget(self.comboBox_21, 0, 11, 1, 1)
        self.comboBox_22 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_22.setObjectName("comboBox_22")
        self.gridLayout.addWidget(self.comboBox_22, 1, 11, 1, 1)
        self.comboBox_23 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_23.setObjectName("comboBox_23")
        self.gridLayout.addWidget(self.comboBox_23, 2, 11, 1, 1)
        self.comboBox_24 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_24.setObjectName("comboBox_24")
        self.gridLayout.addWidget(self.comboBox_24, 3, 11, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 884, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_9.setText(_translate("MainWindow", "受理人员"))
        self.label_4.setText(_translate("MainWindow", "登记日期"))
        self.label_18.setText(_translate("MainWindow", "开发渠道"))
        self.label_2.setText(_translate("MainWindow", "受理日期"))
        self.label_16.setText(_translate("MainWindow", "受理内容"))
        self.label_14.setText(_translate("MainWindow", "姓名"))
        self.label_7.setText(_translate("MainWindow", "至"))
        self.label_6.setText(_translate("MainWindow", "至"))
        self.label_11.setText(_translate("MainWindow", "受理电话"))
        self.label_5.setText(_translate("MainWindow", "至"))
        self.label_17.setText(_translate("MainWindow", "受理类型"))
        self.label_20.setText(_translate("MainWindow", "信息来源"))
        self.label_23.setText(_translate("MainWindow", "状态"))
        self.label_21.setText(_translate("MainWindow", "客户状态"))
        self.label_22.setText(_translate("MainWindow", "渠道名称"))
        self.label_15.setText(_translate("MainWindow", "咨询项目"))
        self.label_10.setText(_translate("MainWindow", "客户卡号"))
        self.label_8.setText(_translate("MainWindow", "至"))
        self.label_3.setText(_translate("MainWindow", "到诊日期"))
        self.label_24.setText(_translate("MainWindow", "QQ"))
        self.label_19.setText(_translate("MainWindow", "受理工具"))
        self.label.setText(_translate("MainWindow", "预约日期"))
        self.label_12.setText(_translate("MainWindow", "开发人员"))
        self.label_13.setText(_translate("MainWindow", "部门"))

